# ==============================
# PREPROCESSING CONFIGURATION
# ==============================
# This file documents all preprocessing decisions based on EDA findings
# Every decision here is based on EDA analysis

# ==============================
# PROJECT METADATA
# ==============================
# Author : Maxwell Selassie Hiamatsu
# Date : 28 / 10 / 2025
# Dataset : e-commerce.csv
# EDA version : 1.0

# ==============================

project:
  name: 'Maxwell Selassie Hiamatsu'
  version: 1.0
  description: Customer Churn Prediction 

# file paths
file_paths:
  raw_data: 'data/raw/e-commerce.csv'
  preprocessed_data: 'data/processed/cleaned_e-commerce.csv'
  scalar_path: 'models/scalar.pkl'
  encoder_path: 'models/encoder.pkl'

# Columns to drop
columns_to_drop:
  action: 'CustomerID'
  reason: 'An identifier. Not predictive'
  eda_evidence: 'CustomerID.png showed a non-predictive pattern'

# handle missing values
missing_values:
  DaySinceLastOrder:
    method: 'median'
    reason: 'Distribution is right-skewed - sensitive to outliers, hence, median imputation'
    eda_evidence: 'DaySinceLastOrder.png showed distribution is right-skewed. 
                  Hence, we imputation is the median of the distribution'

  OrderAmountHikeFromlastYear:
    method: 'median'
    reason: 'Distribution is slightly skewed to the right - hence median imputation'
    eda_evidence: 'OrderHikeAmountFromlastYear.png showed distribution is skewed to the right'

  Tenure:
    method: 'median'
    reason: 'Distribution is very skewed to the right - hence median imputation'
    eda_evidence: 'Tenure.png showed distribution is heavily skewed to the right'

  OrderCount:
    method: 'median'
    reason: 'Distribution is very heavily skewed to the right - hence median imputation'
    eda_evidence: 'OrderCount.png showed distribution is heavily skewed to the right'

  CouponUsed:
  method: 